pipeline{
    agent any

    stages{
        stage('build'){
            steps{
                script{
                    bat '''
                        gradle jar
                        '''
                }
            }
        }

        stage('run'){
            steps{
                script{
                    bat '''
                        java -jar app/build/libs/app.jar
                        '''
                }
            }
        }
    }
}